version: "3"

services:
  dnsmasq:
    image: 4km3/dnsmasq:2.85-r2
    ports:
      - 53:53
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./tftpboot/grub.cfg:/var/lib/tftpboot/grub.cfg
      - ./livecd/EFI/fedora/grubx64.efi:/var/lib/tftpboot/grubx64.efi
      - ./livecd/images/ignition.img:/var/lib/tftpboot/ignition.img
      - ./livecd/images/pxeboot/initrd.img:/var/lib/tftpboot/initrd.img
      - ./livecd/images/pxeboot/vmlinuz:/var/lib/tftpboot/vmlinuz
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./livecd:/usr/share/nginx/html/livecd
      - ./ignition/:/usr/share/nginx/html/ignition
    ports:
      - 80:80
    environment:
      NGINX_PORT: 80
